# Generated by Django 3.1.1 on 2020-09-10 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_update_post', models.DateTimeField(auto_created=True)),
                ('fact_post_date', models.DateTimeField(auto_created=True)),
                ('fact_name', models.TextField(max_length=20)),
                ('fact_body', models.TextField(max_length=400)),
                ('video_link', models.URLField()),
                ('season', models.SmallIntegerField()),
                ('episode', models.SmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
